### ISSUE TITLE
Last version: embed not working - 500 error on redirect to payment

### ISSUE THREAD

**Issue by francowearetonica** [mobbexco/magento#7]

**Comment by jlmobbex** [comment]
Hola @francowearetonica! Gracias por el comentario.
Para resolver el problema nos sería muy útil saber que versiones tenés instaladas (tanto de Magento como del plugin), que configuraciones tenés establecidas actualmente y si hay algún mensaje de error más extenso que nos puedas compartir.

**Comment by jlmobbex** [comment]
@francowearetonica No pudimos reproducir el problema de nuestro lado. En caso de que siga sin funcionar te recomiendo actualizar tanto Magento como el plugin a sus últimas versiones.
